services:
  - type: web
    name: ai-woningadviseur
    env: python
    region: frankfurt
    plan: free

    pythonVersion: "3.11"        # ⇦ dwing Python 3.11 af

    # 📦 Build: alleen Python-packages installeren
    buildCommand: |
      pip install -r requirements.txt

    # 🚀 Start: download Chromium + start gunicorn
    startCommand: >
      bash -c "playwright install chromium --with-deps && gunicorn app:app"

    autoDeploy: true

    envVars:
      - key: OPENAI_API_KEY
        sync: false
