services:
  - type: web
    name: ai-woningadviseur
    env: python
    region: frankfurt
    plan: free

    pythonVersion: "3.11"

    buildCommand: |
      pip install -r requirements.txt

    # Let op: één lange string na >
    startCommand: >
      bash -c "playwright install chromium --with-deps && gunicorn app:app"

    autoDeploy: true

    envVars:
      - key: OPENAI_API_KEY
        sync: false
