services:
  - type: web
    name: ai-woningadviseur
    env: python
    region: frankfurt
    plan: free

    # ⬇️  Build: dependencies + Playwright (zonder browsers)
    buildCommand: |
      pip install -r requirements.txt
      # eventueel extra stappen, maar géén playwright install hier nodig

    # ⬇️  Start: installeert headless-Chromium én start Gunicorn
    startCommand: |
      bash -c "playwright install chromium --with-deps && gunicorn app:app"

    pythonVersion: "3.11"        # ondersteunde versie voor Playwright
    autoDeploy: true

    envVars:
      - key: OPENAI_API_KEY
        sync: false              # sleutel zet je in Render-dashboard
